services:
  - type: web
    name: ollama-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free

    # Disco para modelos
    disk:
      name: ollama-models
      mountPath: /app/models
      sizeGB: 10

    # Variables de entorno
    envVars:
      - key: OLLAMA_HOST
        value: "0.0.0.0"
      - key: OLLAMA_ORIGINS
        value: "*"
      - key: OLLAMA_MODELS
        value: "/app/models"
      - key: OLLAMA_NUM_PARALLEL
        value: "2"
      - key: OLLAMA_MAX_LOADED_MODELS
        value: "1"

    # Health check
    healthCheckPath: "/api/tags"

    # Auto-deploy
    autoDeploy: true

    # Build command opcional
    buildCommand: "echo 'Building Ollama service'"

    # IMPORTANTE: QUITAMOS el startCommand que causaba el error
    # Render usará el CMD del Dockerfile (que debe ejecutar /app/start.sh)
